# Generated by Django 2.2.7 on 2020-02-05 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('factory_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('manufacturing_request_number', models.CharField(blank=True, max_length=30)),
                ('controller_type', models.CharField(blank=True, max_length=30)),
                ('front_panel_module_number', models.IntegerField(blank=True)),
                ('controller_production_date', models.DateField(blank=True)),
                ('qc_date', models.DateField(blank=True)),
                ('metrology_check', models.NullBooleanField()),
                ('project_name', models.CharField(blank=True, max_length=30)),
                ('project_manager_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('factory_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('revision', models.FloatField(blank=True, null=True)),
                ('module_name', models.CharField(blank=True, max_length=30)),
                ('short_module_name', models.CharField(blank=True, max_length=4)),
                ('consignment_number', models.IntegerField(blank=True)),
                ('manufacturer', models.CharField(blank=True, max_length=30)),
                ('production_date', models.DateField(blank=True)),
                ('qc_pass_date', models.DateField(blank=True)),
                ('hash', models.TextField(blank=True)),
                ('engineer_name', models.CharField(blank=True, max_length=30)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ControllerModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Controller')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Module', unique=True)),
            ],
            options={
                'unique_together': {('module', 'controller')},
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField()),
                ('controller_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ControllerModule', unique=True)),
            ],
            options={
                'unique_together': {('slot_number', 'controller_module')},
            },
        ),
    ]
