# Generated by Django 2.2.7 on 2020-02-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200205_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='controller_production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controller',
            name='qc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='consignment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='qc_pass_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
