# Generated by Django 2.2.7 on 2020-02-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_module_short_module_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='front_panel_module_number',
        ),
        migrations.AddField(
            model_name='controller',
            name='another_equipment_numbers',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
