# Generated by Django 2.2.7 on 2020-02-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200205_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllermodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Module', unique=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='controller_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ControllerModule', unique=True),
        ),
    ]
