# Generated by Django 2.2.7 on 2020-02-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200205_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='controller_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
